config:
  perks:
    maxPerks: 4
  gameSettings:
    #Range to allow knife attacks. (Values over 6 are set to 6, the vanilla value.)
    MeleeRange: 2
    #Have all or only one Mystery Box be spawned at a time
    MultipleMysteryBoxes: false
    #Double points length in seconds
    doublePointsTimer: 30
    #Insta kill lenght in seconds
    instaKillTimer: 30
    #Insta kill lenght in seconds
    fireSaleTimer: 30
    #Time perks will stay on the ground in seconds
    perkLife: 15
    #Gun Reload time in seconds
    reloadTime: 3
    #Default points when you hit a zombie, value * 2 on double points
    defaultPointsOnHit: 10
    #Default points when you kill a zombie, value * 2 on double points
    defaultPointsOnKill: 60
    #Max possible zombies in an arena at once
    maxZombies: 20
    #This is the amount to change the zombieSpawnDelay per round. Equation is zombieSpawnDelayFactor / zombieSpawnDelayFactor
    zombieSpawnDelayFactor: 1.05
    #Interval between zombies spawning, value decreases as rounds go up. This value is rounded down and is # of seconds.
    zombieSpawnDelay: 7
    #Time it takes for an arena to start
    arenaStartTime: 60
    #Apply Scope when zooming in if textured
    ZoomTexture: false
    #Change the volume of the round sound
    roundSoundVolume: 0.2
  ReviveSettings:
    ReviveTimer: 4
    ReviveRange: 2
    MaxDownTime: 60
  Economy:
    CostPerJoin: 0
    MoneyPerKill: 1