name: COM_Zombies
main: com.theprogrammingturkey.comz.COMZombies
description: 'Call of Minecraft: Zombies'
version: @version@
authors: [TurkeyDev]
api-version: '1.14'
load: POSTWORLD
softdepend: [Vault, PlaceholderAPI]
